export const engineeringRoles = [
  { title: "Software Engineer" },
  { title: "DevOps Engineer" },
  { title: "Frontend Developer" },
  { title: "Backend Developer" },
  { title: "Full Stack Developer" },
  { title: "Data Scientist" },
  { title: "Machine Learning Engineer" },
  { title: "Data Engineer" },
  { title: "Network Engineer" },
  { title: "Security Engineer" },
  { title: "Cloud Engineer" },
  { title: "Systems Engineer" },
  { title: "QA Engineer" },
  { title: "Site Reliability Engineer" },
  { title: "Mobile Developer" },
  { title: "Game Developer" },
  { title: "Embedded Systems Engineer" },
  { title: "Hardware Engineer" },
  { title: "UI/UX Designer" },
  { title: "Product Manager" },
  { title: "Technical Writer" },
  { title: "Database Administrator" },
  { title: "Web Developer" },
  { title: "Graphics Designer" },
  { title: "User Interface Designer" },
  { title: "User Experience Designer" },
  { title: "Information Technology Manager" },
  { title: "Software Architect" },
  { title: "Enterprise Architect" },
  { title: "Solution Architect" },
  { title: "Technical Support Specialist" },
  { title: "Business Analyst" },
  { title: "Systems Analyst" },
  { title: "Project Manager" },
];

export const location = [{ title: "Remote" }, { title: "In-office" }];

export const minBasePay = [
  { title: "0L" },
  { title: "10L" },
  { title: "20L" },
  { title: "30L" },
  { title: "40L" },
  { title: "50L" },
  { title: "60L" },
  { title: "70L" },
];

export const experience = [
  { title: "1" },
  { title: "2" },
  { title: "3" },
  { title: "4" },
  { title: "5" },
  { title: "6" },
  { title: "7" },
  { title: "8" },
  { title: "9" },
  { title: "10" },
];
